Most overtime points by Florida Panthers players - All-Time 

Data:
https://www.hockey-reference.com/play-index/goal_finder.cgi?request=1&match=goallist&grouping=p&team_id=FLA&season_start=1&season_end=-1&rookie=N&age_min=0&age_max=99&is_playoffs=N&game_num_type=team&game_month=0&game_type%5B%5D=R&game_type%5B%5D=OT&game_type%5B%5D=SO&period%5B%5D=4&order_by=date_game

put in csv file

In [71]:
import pandas as pd 
import numpy as np 
import datetime as dt 

df = pd.read_csv('panthers.csv')
df.index = pd.to_datetime(df.Date)

df.head()

,Rank,Date,Tm,Unnamed: 3,Opp,Unnamed: 5,Unnamed: 6,Scorer,Age,Assist1,Assist2,Goalie,Per.,Time,Strength,Other,Arena Name
Date,,,,,,,,,,,,,,,,,
2019-02-09,1,2/9/19,FLA,@,WSH,W,OT,Mike Hoffman,29.0,Keith Yandle,Aleksander Barkov,Braden Holtby,OT,1:31,PP,NaN,Capital One Arena
2019-02-07,2,2/7/19,FLA,NaN,PIT,W,OT,Mike Matheson,24.0,Jonathan Huberdeau,Aleksander Barkov,Casey DeSmith,OT,4:14,EV,NaN,BB&T Center
2018-12-15,3,12/15/18,FLA,NaN,TOR,W,OT,Aleksander Barkov,23.0,Jonathan Huberdeau,NaN,Frederik Andersen,OT,3:24,EV,NaN,BB&T Center
2018-11-30,4,11/30/18,FLA,NaN,BUF,W,OT,Aleksander Barkov,23.0,Jonathan Huberdeau,Aaron Ekblad,Linus Ullmark,OT,2:26,EV,NaN,BB&T Center
2018-11-26,5,11/26/18,FLA,NaN,NJD,W,OT,Mike Hoffman,29.0,Jonathan Huberdeau,Aaron Ekblad,Keith Kinkaid,OT,1:28,EV,NaN,BB&T Center

In [72]:
df['season_year'] = np.where(df.index.month <= 6, df.index.year - 1, df.index.year)
df_new = df[['Scorer','Assist1','Assist2','season_year']]
df_new = pd.melt(df_new, id_vars=['season_year'], value_vars=['Scorer', 'Assist1','Assist2'])

In [73]:
df_new.head()

   season_year variable              value
0       2018.0   Scorer       Mike Hoffman
1       2018.0   Scorer      Mike Matheson
2       2018.0   Scorer  Aleksander Barkov
3       2018.0   Scorer  Aleksander Barkov
4       2018.0   Scorer       Mike Hoffman

In [74]:
df_new = df_new.sort_values('season_year',ascending = 0)

In [75]:
final = df_new.groupby(['season_year','value']).size()

In [76]:
final = final.sort_values()

In [77]:
final

season_year  value
1993.0       Andrei Lomakin        1
2010.0       David Booth           1
             Bryan Allen           1
2009.0       Stephen Weiss         1
             Shawn Matthias        1
             Nathan Horton         1
             Bryan McCabe          1
             Bryan Allen           1
2008.0       Richard Zednik        1
             Michael Frolik        1
             Keith Ballard         1
             Jay Bouwmeester       1
             David Booth           1
2010.0       Dennis Wideman        1
2008.0       Cory Stillman         1
2007.0       Stephen Weiss         1
             Ruslan Salei          1
             Rostislav Olesz       1
             Magnus Johansson      1
             Jassen Cullimore      1
             Cory Murphy           1
2006.0       Nathan Horton         1
             Martin Gelinas        1
             Jozef Stumpel         1
             Jay Bouwmeester       1
             Ed Belfour            1
2005.0       Steve Montador        1
2008.0       Bryan McCabe          1
2010.0       Dmitry Kulikov        1
             Jason Garrison        1
                                  ..
2005.0       Mike Van Ryn          2
             Stephen Weiss         2
             Joe Nieuwendyk        2
2017.0       Aaron Ekblad          2
2010.0       Cory Stillman         2
2016.0       Mike Matheson         2
2005.0       Chris Gratton         2
2016.0       Jussi Jokinen         2
2002.0       Valeri Bure           2
2016.0       Jon Marchessault      2
2000.0       Pavel Bure            2
1996.0       Per Gustafsson        2
2008.0       Nathan Horton         2
             Stephen Weiss         2
1999.0       Robert Svehla         2
             Pavel Bure            2
2003.0       Mike Van Ryn          2
2016.0       Aleksander Barkov     3
2005.0       Jozef Stumpel         3
2018.0       Mike Hoffman          3
2003.0       Olli Jokinen          3
2007.0       Nathan Horton         3
2016.0       Vincent Trocheck      3
2002.0       Olli Jokinen          3
2006.0       Stephen Weiss         3
2007.0       Olli Jokinen          3
2010.0       Stephen Weiss         3
2018.0       Jonathan Huberdeau    4
             Aleksander Barkov     5
2005.0       Olli Jokinen          6
Length: 141, dtype: int64